<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'Twig_Extensions_' => array($vendorDir . '/slim/extras/Views/Extension'),
    'Slim\\Extras' => array($vendorDir . '/slim/extras'),
    'Slim' => array($vendorDir . '/slim/slim'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log'),
    'Doctrine\\Common\\Lexer\\' => array($vendorDir . '/doctrine/lexer/lib'),
    'Doctrine\\Common\\Annotations\\' => array($vendorDir . '/doctrine/annotations/lib'),
    'API' => array($baseDir . '/api'),
    'Evenement' => array($vendorDir . '/evenement/evenement/src'),
);
