<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'Symfony\\Polyfill\\Php56\\' => array($vendorDir . '/symfony/polyfill-php56'),
    'Symfony\\Polyfill\\Php55\\' => array($vendorDir . '/symfony/polyfill-php55'),
    'Symfony\\Component\\Yaml\\' => array($vendorDir . '/symfony/yaml'),
    'Symfony\\Component\\Finder\\' => array($vendorDir . '/symfony/finder'),
    'Swagger\\' => array($vendorDir . '/zircote/swagger-php/src'),
    'Joomla\\Utilities\\Tests\\' => array($vendorDir . '/joomla/utilities/Tests'),
    'Joomla\\Utilities\\' => array($vendorDir . '/joomla/utilities/src'),
    'Joomla\\Uri\\Tests\\' => array($vendorDir . '/joomla/uri/Tests'),
    'Joomla\\Uri\\' => array($vendorDir . '/joomla/uri/src'),
    'Joomla\\String\\Tests\\' => array($vendorDir . '/joomla/string/Tests'),
    'Joomla\\String\\' => array($vendorDir . '/joomla/string/src'),
    'Joomla\\Registry\\Tests\\' => array($vendorDir . '/joomla/registry/Tests'),
    'Joomla\\Registry\\' => array($vendorDir . '/joomla/registry/src'),
    'Joomla\\Input\\Tests\\' => array($vendorDir . '/joomla/input/Tests'),
    'Joomla\\Input\\' => array($vendorDir . '/joomla/input/src'),
    'Joomla\\Http\\Tests\\' => array($vendorDir . '/joomla/http/Tests'),
    'Joomla\\Http\\' => array($vendorDir . '/joomla/http/src'),
    'Joomla\\Filter\\Tests\\' => array($vendorDir . '/joomla/filter/Tests'),
    'Joomla\\Filter\\' => array($vendorDir . '/joomla/filter/src'),
    'Joomla\\DI\\Tests\\' => array($vendorDir . '/joomla/di/Tests'),
    'Joomla\\DI\\' => array($vendorDir . '/joomla/di/src'),
    'Joomla\\Application\\Tests\\' => array($vendorDir . '/joomla/application/Tests'),
    'Joomla\\Application\\' => array($vendorDir . '/joomla/application/src'),
    'RingCentral\\Psr7\\' => array($vendorDir . '/ringcentral/psr7/src'),
    'React\\Stream\\' => array($vendorDir . '/react/stream/src'),
    'React\\Socket\\' => array($vendorDir . '/react/socket/src'),
    'React\\Promise\\Timer\\' => array($vendorDir . '/react/promise-timer/src'),
    'React\\Promise\\' => array($vendorDir . '/react/promise/src'),
    'React\\Http\\' => array($vendorDir . '/react/http/src'),
    'React\\HttpClient\\' => array($vendorDir . '/react/http-client/src'),
    'React\\EventLoop\\' => array($vendorDir . '/react/event-loop/src'),
    'React\\Dns\\' => array($vendorDir . '/react/dns/src'),
    'React\\Datagram\\' => array($vendorDir . '/react/datagram/src'),
    'React\\Cache\\' => array($vendorDir . '/react/cache/src'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
);
